"""BenchmarkRunner — orchestrates strategy benchmarking end-to-end.

Loads a strategy via its slug, fetches price data, splits into
train/OOS periods, runs backtest via vectorbt_bridge, computes
extended metrics, and writes benchmark_results.json atomically.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from datetime import date, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from alphakit.bench import discovery, metrics
from alphakit.bridges import vectorbt_bridge


def _get_commit_sha() -> str | None:
    """Get current git commit SHA, or None if not in a git repo."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            return result.stdout.strip()[:12]
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return None


class BenchmarkRunner:
    """Run a strategy benchmark and produce benchmark_results.json.

    Parameters
    ----------
    commission_bps
        Round-trip commission in basis points.
    data_start
        Start date for price data (training begins here).
    in_sample_end
        End of in-sample / start of out-of-sample.
    out_of_sample_end
        End of out-of-sample period.
    initial_cash
        Starting cash for the backtest.
    """

    def __init__(
        self,
        *,
        commission_bps: float = 5.0,
        data_start: str = "2005-01-01",
        in_sample_end: str = "2019-12-31",
        out_of_sample_end: str = "2025-12-31",
        initial_cash: float = 100_000.0,
    ) -> None:
        self.commission_bps = commission_bps
        self.data_start = data_start
        self.in_sample_end = in_sample_end
        self.out_of_sample_end = out_of_sample_end
        self.initial_cash = initial_cash

    def run_single(
        self,
        slug: str,
        prices: pd.DataFrame | None = None,
        *,
        family: str | None = None,
    ) -> dict[str, Any]:
        """Benchmark a single strategy, returning the Appendix C dict.

        Parameters
        ----------
        slug
            Strategy slug (e.g. ``"tsmom_12_1"``).
        prices
            Optional pre-loaded price DataFrame. If None, attempts to
            load from alphakit-data fixtures or yfinance.
        family
            Strategy family. Auto-detected from slug if not provided.
        """
        if family is None:
            family, slug = discovery.find_strategy(slug)

        strategy = discovery.instantiate(family, slug)
        config = discovery.load_config(family, slug)
        universe = config.get("universe", ["SPY", "EFA", "AGG"])

        # Get price data
        if prices is None:
            prices = self._fetch_prices(universe)

        # Filter to OOS period only for benchmark metrics
        oos_start = pd.Timestamp(self.in_sample_end) + pd.Timedelta(days=1)
        oos_end = pd.Timestamp(self.out_of_sample_end)

        # But we need the full history for warm-up — run on all data,
        # then slice metrics to OOS period
        full_result = vectorbt_bridge.run(
            strategy=strategy,
            prices=prices,
            initial_cash=self.initial_cash,
            commission_bps=self.commission_bps,
        )

        # Slice to OOS period for metrics
        oos_mask = (full_result.returns.index >= oos_start) & (
            full_result.returns.index <= oos_end
        )
        oos_returns = full_result.returns[oos_mask]
        oos_weights = full_result.weights[oos_mask]

        # If not enough OOS data, fall back to full period
        if len(oos_returns) < 60:
            oos_returns = full_result.returns
            oos_weights = full_result.weights

        # Compute metrics
        returns_arr = oos_returns.to_numpy()
        from alphakit.core.metrics.drawdown import max_drawdown
        from alphakit.core.metrics.returns import calmar_ratio, sharpe_ratio, sortino_ratio

        sharpe = sharpe_ratio(returns_arr)
        sortino = sortino_ratio(returns_arr)
        calmar = calmar_ratio(returns_arr)
        mdd = max_drawdown(returns_arr)
        ann_ret = float(np.mean(returns_arr) * 252) if len(returns_arr) > 0 else 0.0
        ann_vol = (
            float(np.std(returns_arr, ddof=1) * np.sqrt(252))
            if len(returns_arr) > 1
            else 0.0
        )

        # Extended metrics
        to = metrics.turnover_annual(oos_weights)
        cap = metrics.capacity_estimate_bn(to)
        regime = metrics.regime_performance(oos_returns)

        result = {
            "slug": slug,
            "status": "populated",
            "note": "Generated by alphakit-bench BenchmarkRunner.",
            "benchmark_date": date.today().isoformat(),
            "data_start": self.data_start,
            "in_sample_end": self.in_sample_end,
            "out_of_sample_end": self.out_of_sample_end,
            "universe": universe,
            "metrics": {
                "sharpe": round(sharpe, 4),
                "sortino": round(sortino, 4),
                "calmar": round(calmar, 4),
                "max_drawdown": round(mdd, 4),
                "annualized_return": round(ann_ret, 4),
                "annualized_vol": round(ann_vol, 4),
                "turnover_annual": round(to, 2),
                "capacity_usd_bn": round(cap, 1),
            },
            "regime_performance": {
                k: round(v, 4) for k, v in regime.items()
            },
            "transaction_costs_assumed_bps": self.commission_bps,
            "commit_sha": _get_commit_sha(),
            "engine": "vectorbt",
        }
        return result

    def write_benchmark(
        self,
        slug: str,
        result: dict[str, Any],
        *,
        family: str | None = None,
    ) -> Path:
        """Write benchmark_results.json atomically with backup.

        Returns the path to the written file.
        """
        if family is None:
            family, slug = discovery.find_strategy(slug)

        path = discovery.benchmark_results_path(family, slug)

        # Backup existing file
        if path.exists():
            backup = path.with_suffix(".json.bak")
            shutil.copy2(path, backup)

        # Atomic write via temp file
        tmp = path.with_suffix(".json.tmp")
        with open(tmp, "w") as f:
            json.dump(result, f, indent=2, default=str)
            f.write("\n")
        tmp.rename(path)
        return path

    def _fetch_prices(self, universe: list[str]) -> pd.DataFrame:
        """Fetch prices for the given universe.

        Tries yfinance adapter first, falls back to fixture data.
        """
        try:
            from alphakit.data.equities.yfinance_adapter import YFinanceAdapter

            adapter = YFinanceAdapter()
            return adapter.fetch(
                symbols=universe,
                start=datetime.fromisoformat(self.data_start),
                end=datetime.fromisoformat(self.out_of_sample_end),
            )
        except (ImportError, Exception):
            pass

        # Fall back to fixture data
        from alphakit.data.fixtures.generator import generate_fixture_prices

        return generate_fixture_prices(
            symbols=universe,
            start=self.data_start,
            end=self.out_of_sample_end,
        )
